apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-client
    appGroup: MySpringApp
  name: admin-client-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: admin-client
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
