apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminclient
    appGroup: MySpringApp
  name: admin-client-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app: adminclient
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}