apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin-tracing
    purpose: precious
  name: zipkin-tracing-service
  namespace: voyager-ns
spec:
  ports:
  - nodePort: 32326
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: zipkin-tracing
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
