apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin-tracing
  name: zipkin-tracing-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32326
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: zipkin-tracing
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
