apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employee-app
  name: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  strategy: {}
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
      - image: demospringapp/employee:1
        name: employee-app
        ports:
        - containerPort: 8082
        env:
          - name: DB_HOST
            value: 10.96.103.168
          - name: DB_PORT
            value: "3306"
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: root
          - name: EUREKA_HOST
            value: 10.96.184.127
          - name: EUREKA_PORT
            value: "8761"
        resources: {}
status: {}
