apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-app
    appGroup: MySpringApp
  name: employee-app-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: employee-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
