apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMTEzNzA3OTcyMDIuZGtyLmVjci51cy13ZXN0LTIuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSIzNzU4OTA5NDg0ODIuZGtyLmVjci51cy1lYXN0LTIuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSJwdWJsaWMuZWNyLmF3cyI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==

