apiVersion: v1
kind: Service
metadata:
  labels:
    app: connector-app
    appGroup: MySpringApp
  name: connector-app-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: connector-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
