apiVersion: v1
kind: Service
metadata:
  labels:
    app: demospringapp
    appGroup: MySpringApp
    purpose: precious
  name: apigateway-service
  namespace: voyager-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demospringapp
  type: LoadBalancer
