apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
      containers:
      - name: rabbitmq-container
        image: rabbitmq:latest
        ports:
        - containerPort: 5672  # RabbitMQ default port
        - containerPort: 15672 # RabbitMQ Management UI
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
