apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-db
spec:
  selector:
    matchLabels:
      app: employee-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: employee-db
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              value: company
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql2-pvc
