apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql  # Replace with your host path

