apiVersion: v1
kind: Service
metadata:
  name: employee-db-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: employee-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
