apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-21T18:13:07Z"
  name: employee-db
  namespace: default
  resourceVersion: "69691"
  uid: ffe021a2-b8d7-4b7f-a470-c14ed1da5c63
spec:
  clusterIP: 10.96.103.168
  clusterIPs:
  - 10.96.103.168
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: employee-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
