apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-registry
    purpose: precious
  name: service-registry
  namespace: voyager-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  strategy: {}
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
      - name: registrysecret
      containers:
      - image: symphony-docker-local.jfrog.io/demospringapp/serviceregistry:1
        name: service-registry
        ports:
        - containerPort: 8761
        resources: {}
status: {}
