apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-registry
    purpose: precious
  name: service-registry-service
  namespace: voyager-ns
spec:
  ports:
  - nodePort: 31216
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: service-registry
  type: NodePort
status:
  loadBalancer: {}
