apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-registry
  name: service-registry-service
  namespace: default
spec:
  ports:
  - nodePort: 31216
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: service-registry
  type: LoadBalancer
status:
  loadBalancer: {}
