apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-registry
  name: service-registry-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31216
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: service-registry
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
