apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-registry
  name: service-registry-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8761
  selector:
    app: service-registry
  type: LoadBalancer