apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student-app
    appGroup: MySpringApp
  name: student-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  strategy: {}
  template:
    metadata:
      labels:
        app: student-app
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
      - image: demospringapp/student:1
        name: student-app
        ports:
        - containerPort: 8081
        env:
          - name: DB_HOST
            value: student-db-service
          - name: DB_PORT
            value: "3306"
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: root
          - name: EUREKA_HOST
            value: service-registry-service
          - name: EUREKA_PORT
            value: "8761"
          - name: ZIPKIN_HOST
            value: zipkin-tracing-service
          - name: ZIPKIN_PORT
            value: "9411"
        resources: {}
status: {}
