apiVersion: v1
kind: Service
metadata:
  labels:
    app: student-app
    appGroup: MySpringApp
  name: student-app-service
  namespace: default
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: student-app
  type: ClusterIP
