apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-21T17:53:44Z"
  labels:
    app: student-app
  name: student-app
  namespace: default
  resourceVersion: "68050"
  uid: a889c2bf-e5d0-45df-92cf-e0db732c0e90
spec:
  clusterIP: 10.96.96.12
  clusterIPs:
  - 10.96.96.12
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: student-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
