apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-db
  namespace: voyager-ns
  labels:
    app: student-db
    purpose: precious
spec:
  selector:
    matchLabels:
      app: student-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: student-db
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              value: school
          ports:
            - containerPort: 3306
              name: mysql