apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-23T12:33:03Z"
  name: student-db
  namespace: default
  resourceVersion: "117629"
  uid: 0f059ddd-4447-46af-94d8-538fc985169b
spec:
  clusterIP: 10.96.253.49
  clusterIPs:
  - 10.96.253.49
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: student-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
