apiVersion: v1
kind: Service
metadata:
  name: student-db-service
  namespace: voyager-ns
  labels:
    purpose: precious
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: student-db
  type: ClusterIP
status:
  loadBalancer: {}
