# eks-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aniket-eks-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    desiredCapacity: 2
    instanceType: t3.micro
    labels:
      affinity: group-1

  - name: ng-2
    desiredCapacity: 2
    instanceType: t3.small
    labels:
      affinity: group-2

