apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messaging-app
  name: messaging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  strategy: {}
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
      - image: demospringapp/messaging:1
        name: messaging-app
        ports:
        - containerPort: 8083
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq-service
          - name: RABBITMQ_PORT
            value: "5672"
          - name: EUREKA_HOST
            value: service-registry-service
          - name: EUREKA_PORT
            value: "8761"
          - name: ZIPKIN_HOST
            value: zipkin-tracing-service
          - name: ZIPKIN_PORT
            value: "9411"
        resources: {}
status: {}
