apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messaging-app
  name: messaging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  strategy: {}
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
      - image: demospringapp/messaging:1
        name: messaging-app
        ports:
        - containerPort: 8083
        env:
          - name: RABBITMQ_HOST
            value: 10.96.51.88
          - name: RABBITMQ_PORT
            value: "5672"
        resources: {}
status: {}
