apiVersion: v1
kind: Service
metadata:
  labels:
    app: messaging-app
    appGroup: MySpringApp
  name: messaging-app-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: messaging-app
  type: ClusterIP
