apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-21T18:22:24Z"
  labels:
    app: messaging-app
  name: messaging-app
  namespace: default
  resourceVersion: "70479"
  uid: 31bd1cb4-6754-4a33-a73a-3bdda0ac8139
spec:
  clusterIP: 10.96.189.45
  clusterIPs:
  - 10.96.189.45
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: messaging-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
