apiVersion: v1
kind: Service
metadata:
  labels:
    app: messaging-app
  name: messaging-queue-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: messaging-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
