apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jmxconnector-app
    appGroup: MySpringApp
  name: jmxconnector-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmxconnector-app
  strategy: {}
  template:
    metadata:
      labels:
        app: jmxconnector-app
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
      - image: jmxconnector-app:7
        name: jmxconnector-app
        ports:
        - containerPort: 8099
        env:
          - name: JMX_HOST_DOMAIN
            value: 10.244.0.56
          - name: JMX_PORT
            value: "9090"
        resources: {}
status: {}
