apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demospringapp
  name: demospringapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demospringapp
  strategy: {}
  template:
    metadata:
      labels:
        app: demospringapp
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
      - image: demospringapp/demospringapp:1
        name: demospringapp
        ports:
        - containerPort: 8080
        env:
          - name: STUDENT_HOST
            value: 10.96.96.12
          - name: STUDENT_PORT
            value: "8081"
          - name: EMPLOYEE_HOST
            value: 10.96.241.199
          - name: EMPLOYEE_PORT
            value: "8082"
          - name: MESSAGE_HOST
            value: 10.96.189.45
          - name: MESSAGE_PORT
            value: "8083"

        resources: {}
status: {}
