apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminserver
    appGroup: MySpringApp
  name: adminserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminserver
  strategy: {}
  template:
    metadata:
      labels:
        app: adminserver
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
        - image: demospringapp/adminserver:1
          name: adminserver
          ports:
            - containerPort: 8089
          resources: {}
status: {}