apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminserver
    appGroup: MySpringApp
    purpose: precious
  name: adminserver
  namespace: voyager-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminserver
  strategy: {}
  template:
    metadata:
      labels:
        app: adminserver
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: registrysecret
      containers:
      - image: symphony-docker-local.jfrog.io/demospringapp/adminserver:3
        name: adminserver
        ports:
        - containerPort: 8089
        resources: {}
status: {}
