apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminserver
    appGroup: MySpringApp
  name: adminserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminserver
  strategy: {}
  template:
    metadata:
      labels:
        app: adminserver
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - image: 111370797202.dkr.ecr.us-west-2.amazonaws.com/demospringapp/adminserver:3
        name: adminserver
        ports:
        - containerPort: 8089
        resources: {}
status: {}
