apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
    appGroup: MySpringApp
  name: admin-server-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: admin-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
