apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminserver
    appGroup: MySpringApp
  name: admin-server-service
  namespace: default
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: adminserver
  type: ClusterIP
status:
  loadBalancer: {}
