apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminserver
    appGroup: MySpringApp
  name: admin-server-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: adminserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}